{{- if eq .Values.gotk.networkPolicy.enabled true -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/version: latest
  name: allow-scraping
  namespace: {{.Release.Namespace}}
spec:
  ingress:
    - from:
        {{- if .Values.gotk.networkPolicy.namespaceSelector }}
        - namespaceSelector: {{ toYaml .Values.gotk.networkPolicy.namespaceSelector | trim | nindent 12 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - port: 8080
          protocol: TCP
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/version: latest
  name: deny-ingress
  namespace: {{.Release.Namespace}}
spec:
  egress:
    - {}
  ingress:
    - from:
        - podSelector: {}
        {{- if .Values.gotk.networkPolicy.namespaceSelector }}
        - namespaceSelector: {{ toYaml .Values.gotk.networkPolicy.namespaceSelector | trim | nindent 12 }}
        {{- end }}
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end -}}
